### ISSUE TITLE
Please check this with your instructor if you are taking the course at UW-Madison. Otherwise, you don't have access.

### ISSUE THREAD

**Issue by xiaoheling** [edydfang/Bourbon#3]
excuse me，is there any other ways to reproduce this experiment，i do not have the access to this course？

Please check this with your instructor if you are taking the course at UW-Madison. Otherwise, you don't have access.

_Originally posted by @edydfang in https://github.com/edydfang/Bourbon/issues/2#issuecomment-1005328006_

**Comment by edydfang** [comment]
> excuse me，is there any other ways to reproduce this experiment，i do not have the access to this course？
> 
> Please check this with your instructor if you are taking the course at UW-Madison. Otherwise, you don't have access.
> 
> _Originally posted by @edydfang in [#2 (comment)](https://github.com/edydfang/Bourbon/issues/2#issuecomment-1005328006)_

I would assume you can run the project on any Linux machine. Any specific issue you met?
