### ISSUE TITLE
Confirm the implements and improments

### ISSUE THREAD

**Issue by JiananYuan** [edydfang/Bourbon#4]
Hello, nice to discover your Bourbon project! In README, you said that you further utilize the model to speed up the lookup process at each level to find files. Does it mean that you not only implemented Bourbon in the paper, but also made some improvements? Thank you!

**Comment by edydfang** [comment]
> 

The original implementation is done by the paper author in UW-Madison. My classmate and I only add a minor improvement over the implementation.

**Comment by JiananYuan** [comment]
Hi! So nice to read the code in your project! I wonder whether there exist any differences among the three branches (i.e., master, async, and async-level_learning)? If I want to develop based on the original Bourbon published in OSDI(2020), which branch should I choose? Besides, is it possible that I can run `/scripts/run_all_expr.sh` on my own x86_Linux machine (6 CPU plus 8G memory plus 20G storage) despite I cannot get access to UW-Madison? Thank you so much!

**Comment by edydfang** [comment]
> Hi! So nice to read the code in your project! I wonder whether there exist any differences among the three branches (i.e., master, async, and async-level_learning)? If I want to develop based on the original Bourbon published in OSDI(2020), which branch should I choose? Besides, is it possible that I can run `/scripts/run_all_expr.sh` on my own x86_Linux machine (6 CPU plus 8G memory plus 20G storage) despite I cannot get access to UW-Madison? Thank you so much!

https://github.com/edydfang/Bourbon/tree/ad6abcb6ac879122dbd97f89818a4ff0960138f8
This commit is for the original bourbon.
I think your machine should be enough for testing. It depends on the benchmark size though. You can try it out.

**Comment by JiananYuan** [comment]
thanks a lot
