### ISSUE TITLE
Read_cold

### ISSUE THREAD

**Issue by studyzsy** [edydfang/Bourbon#6]
Where is read_cold application?

**Comment by edydfang** [comment]
You wouldn't ask this question if you did a simple serach: https://github.com/edydfang/Bourbon/blob/49f41bdbd8ebf19824b25efe802686e3881764fc/CMakeLists.txt#L387

**Comment by studyzsy** [comment]
Thank you! But when I run the code like "scripts/run_load_order.sh" prompt "Segmentation fault      (core dumped)".

**Comment by edydfang** [comment]
> Thank you! But when I run the code like "scripts/run_load_order.sh" prompt "Segmentation fault (core dumped)".

You are suppose to troubleshot such kind of crash bug which is supposed to be a basic skill when developing C/C++ program. Feel free to create a PR if you think it's a legitmate bug.

**Comment by quxiuchuan** [comment]
> Thank you! But when I run the code like "scripts/run_load_order.sh" prompt "Segmentation fault (core dumped)".

I have the same situation. Have you solved this problem? Could you tell the method? Thanks.
